name: Upload to ESOUI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.github/**'
      - '*.md'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip addon folder
        run: |
          zip -r SkillLines.zip SkillLines


      - name: Upload to ESOUI
        uses: m00nyONE/esoui-upload@v1
        with:
          api_key: ${{ secrets.ESOUI_ADDON_UPDATE }}
          addon_id: 4041
          version: v2.0.0
          zip_file: SkillLines.zip
          changelog_file: CHANGELOG.txt


      - name: Update version badge in README
        run: |
          sed -i -E "s/version-v[0-9]+\.[0-9]+\.[0-9]+/version-${VERSION}/" README.md

      - name: Commit README change
        uses: EndBug/add-and-commit@v9
        with:
          add:      README.md
          message:  "docs: bump README to ${VERSION} [skip ci]"